module : CollectionView
skip_undocumented: true
clean : true
theme : fullwidth
min_acl : public
author : Wes Byrne
readme : ./README.md
github_url : https://github.com/TheNounProject/CollectionView
hide_documentation_coverage : true
